# Generated by Django 6.0.1 on 2026-01-22 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration_days', models.PositiveIntegerField()),
                ('payment_mode', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('one_time', 'One Time')], max_length=20)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_roi_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('roi_start_after_days', models.PositiveIntegerField(help_text='Days after completion before ROI starts')),
                ('allows_early_completion', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('investment_type', models.CharField(choices=[('farmland', 'Farmland'), ('terrace', 'Terrace')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('duration_days', models.PositiveIntegerField()),
                ('expected_roi_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('payment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.investmentplan')),
            ],
        ),
    ]
