# Generated by Django 6.0.1 on 2026-02-03 09:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration_days', models.PositiveIntegerField()),
                ('payment_mode', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('one_time', 'One Time')], db_index=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('investment_type', models.CharField(choices=[('agriculture', 'Agriculture'), ('real-estate', 'Real Estate')], db_index=True, max_length=20)),
                ('asset_type', models.CharField(choices=[('terrace', 'Terrace')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('investment_detail', models.TextField()),
                ('roi_start_after_days', models.PositiveIntegerField(help_text='Days after completion before ROI starts')),
                ('project_img', models.ImageField(blank=True, null=True, upload_to='project_img/')),
                ('expected_roi_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('minimum_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.investmentplan')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_options', to='investment.investmentproject')),
            ],
        ),
        migrations.CreateModel(
            name='ClientInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('installment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('next_payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Deposit'), ('paying', 'Ongoing Payment'), ('completed', 'Completed'), ('earning', 'Earning Returns')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investment.projectpricing')),
            ],
            options={
                'verbose_name': 'Client Investment',
                'verbose_name_plural': 'Client Investments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('installment_number', models.PositiveIntegerField(default=1)),
                ('due_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('pending', 'Pending (Due)'), ('paid', 'Paid'), ('overdue', 'Overdue')], db_index=True, default='upcoming', max_length=20)),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('proof_of_payment', models.FileField(blank=True, null=True, upload_to='payment_proofs/')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='investment.clientinvestment')),
            ],
            options={
                'verbose_name': 'Payment Schedule',
                'verbose_name_plural': 'Payment Schedules',
                'ordering': ['installment_number'],
                'indexes': [models.Index(fields=['status', 'due_date'], name='investment__status_ce571d_idx')],
                'unique_together': {('investment', 'installment_number')},
            },
        ),
        migrations.AddConstraint(
            model_name='projectpricing',
            constraint=models.UniqueConstraint(fields=('project', 'plan'), name='unique_project_plan'),
        ),
    ]
