# Generated by Django 6.0.1 on 2026-01-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentplan',
            name='expected_roi_percent',
        ),
        migrations.RemoveField(
            model_name='investmentplan',
            name='roi_start_after_days',
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='roi_start_after_days',
            field=models.PositiveIntegerField(default=30, help_text='Days after completion before ROI starts'),
            preserve_default=False,
        ),
    ]
