# Generated by Django 6.0.1 on 2026-02-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentproject',
            name='asset_type',
            field=models.CharField(choices=[('terrace', 'Terrace'), ('farmland', 'Farmland')], max_length=20),
        ),
    ]
