# Generated by Django 6.0.1 on 2026-01-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentproject',
            name='asset_type',
            field=models.CharField(choices=[('terrace', 'Terrace')], default='terrace', max_length=20),
            preserve_default=False,
        ),
    ]
