# Generated by Django 6.0.1 on 2026-01-22 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_remove_investmentplan_expected_roi_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentproject',
            name='duration_days',
        ),
    ]
