# Generated by Django 6.0.1 on 2026-02-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_alter_investmentproject_asset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentplan',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
