# Generated by Django 6.0.1 on 2026-01-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_investmentproject_asset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinvestment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='clientinvestment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Deposit'), ('paying', 'Ongoing Payment'), ('completed', 'Completed'), ('earning', 'Earning Returns')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='payment_mode',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('one_time', 'One Time')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='investment_type',
            field=models.CharField(choices=[('agriculture', 'Agriculture'), ('real-estate', 'Real Estate')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='due_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('pending', 'Pending (Due)'), ('paid', 'Paid'), ('overdue', 'Overdue')], db_index=True, default='upcoming', max_length=20),
        ),
        migrations.AddIndex(
            model_name='paymentschedule',
            index=models.Index(fields=['status', 'due_date'], name='investment__status_ce571d_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectpricing',
            constraint=models.UniqueConstraint(fields=('project', 'plan'), name='unique_project_plan'),
        ),
    ]
