# Generated by Django 6.0.1 on 2026-01-22 11:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_remove_investmentproject_duration_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentplan',
            old_name='max_amount',
            new_name='amount_per_time',
        ),
        migrations.RemoveField(
            model_name='investmentplan',
            name='min_amount',
        ),
        migrations.CreateModel(
            name='ClientInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_deadline', models.DateField()),
                ('status', models.CharField(choices=[('paying', 'Ongoing Payment'), ('completed', 'Completed'), ('earning', 'Earning Returns')], default='paying', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investment.investmentplan')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.investmentproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
