# Generated by Django 6.0.1 on 2026-02-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_alter_investmentplan_duration_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentplan',
            name='duration_days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
