# Generated by Django 6.0.1 on 2026-01-22 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0004_rename_max_amount_investmentplan_amount_per_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientinvestment',
            old_name='total_amount',
            new_name='agreed_amount',
        ),
        migrations.RemoveField(
            model_name='clientinvestment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='clientinvestment',
            name='payment_deadline',
        ),
        migrations.RemoveField(
            model_name='clientinvestment',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='clientinvestment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='investmentplan',
            name='active',
        ),
        migrations.RemoveField(
            model_name='investmentplan',
            name='allows_early_completion',
        ),
        migrations.RemoveField(
            model_name='investmentplan',
            name='amount_per_time',
        ),
        migrations.RemoveField(
            model_name='investmentplan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='investmentproject',
            name='payment_plan',
        ),
        migrations.AddField(
            model_name='clientinvestment',
            name='next_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientinvestment',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clientinvestment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Deposit'), ('paying', 'Ongoing Payment'), ('completed', 'Completed'), ('earning', 'Earning Returns')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='payment_mode',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('one_time', 'One Time')], max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investment.clientinvestment')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('minimum_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.investmentplan')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_options', to='investment.investmentproject')),
            ],
        ),
        migrations.AddField(
            model_name='clientinvestment',
            name='selected_option',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='investment.projectpricing'),
            preserve_default=False,
        ),
    ]
