# Generated by Django 6.0.1 on 2026-01-22 12:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0005_rename_total_amount_clientinvestment_agreed_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinvestment',
            name='installment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='clientinvestment',
            name='agreed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='clientinvestment',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='PaymentTransaction',
        ),
    ]
