# Generated by Django 6.0.1 on 2026-01-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0007_alter_projectpricing_minimum_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpricing',
            name='minimum_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
